name: Audit

on:
  schedule:
    - cron: "34 6 * * *"
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  

env:
  CARGO_TERM_COLOR: always

jobs:
  security_audit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-deny
    - name: Scan for vulnerabilities
      run: cargo deny check advisories
